"use client";
import {useMemo,useState} from "react";
type Asset={rank:number;symbol:string;name:string;price:string;change:number;score:number;direction:string;confidence:number;risk:string;fund:number;tech:number;whale:number;deriv:number;spark:number[]};
const assets:Asset[]=[
{rank:1,symbol:"BTC",name:"Bitcoin",price:"$112,486.20",change:2.84,score:86,direction:"LONG",confidence:78,risk:"LOW",fund:88,tech:82,whale:91,deriv:76,spark:[32,38,35,44,48,46,57,62,59,69,74,81]},
{rank:2,symbol:"ETH",name:"Ethereum",price:"$4,286.14",change:4.12,score:83,direction:"LONG",confidence:74,risk:"MED",fund:84,tech:87,whale:76,deriv:81,spark:[28,31,38,35,42,51,48,58,64,62,73,79]},
{rank:3,symbol:"SOL",name:"Solana",price:"$196.72",change:6.31,score:79,direction:"LONG",confidence:69,risk:"MED",fund:76,tech:91,whale:74,deriv:71,spark:[25,29,37,34,49,44,55,61,58,72,68,82]},
{rank:4,symbol:"LINK",name:"Chainlink",price:"$24.83",change:3.45,score:75,direction:"WATCH",confidence:64,risk:"MED",fund:82,tech:69,whale:79,deriv:66,spark:[42,39,44,46,45,52,50,55,54,61,59,64]},
{rank:5,symbol:"AVAX",name:"Avalanche",price:"$31.56",change:-1.26,score:68,direction:"WATCH",confidence:58,risk:"HIGH",fund:71,tech:62,whale:68,deriv:59,spark:[68,64,66,59,62,55,58,51,49,53,47,45]},
{rank:6,symbol:"XRP",name:"XRP",price:"$2.91",change:-2.18,score:61,direction:"SHORT",confidence:66,risk:"HIGH",fund:64,tech:51,whale:58,deriv:72,spark:[72,69,71,65,61,63,55,57,49,45,48,39]}];
const nav=["Overview","Markets","Intelligence","Signals","Backtests","Portfolio"],scans=["Strongest longs","Whale accumulation","Technical breakout","News catalyst"];
function Sparkline({data,down=false}:{data:number[];down?:boolean}){const pts=data.map((v,i)=>`${i*10},${34-(v-20)*.42}`).join(" ");return <svg className="spark" viewBox="0 0 110 38"><polyline points={pts} fill="none" stroke={down?"#ff5d73":"#53e0ad"} strokeWidth="2"/><polyline points={`0,38 ${pts} 110,38`} fill={down?"#ff5d7314":"#53e0ad14"}/></svg>}
function Ring({v}:{v:number}){return <div className="ring" style={{background:`conic-gradient(#53e0ad ${v*3.6}deg,#1b2729 0)`}}><span>{v}</span></div>}
export default function Home(){const[active,setActive]=useState("Overview"),[selected,setSelected]=useState(assets[0]),[search,setSearch]=useState(""),[scan,setScan]=useState(scans[0]),[notice,setNotice]=useState("");const filtered=useMemo(()=>assets.filter(a=>(a.symbol+a.name).toLowerCase().includes(search.toLowerCase())),[search]);const notify=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2200)};return <main>
<aside className="sidebar"><div className="brand"><span className="brandMark">Ø</span><div><strong>ORBITAL</strong><small>INTELLIGENCE</small></div></div><nav>{nav.map((n,i)=><button key={n} className={active===n?"active":""} onClick={()=>setActive(n)}><span>{["⌁","◫","◇","⌁","◷","◉"][i]}</span>{n}</button>)}</nav><div className="sideFoot"><span className="statusDot"/> SYSTEMS OPERATIONAL<small>7 providers connected</small></div></aside>
<section className="workspace"><header><div className="mobileBrand">Ø ORBITAL</div><div className="marketState"><span className="pulse"/> MARKET REGIME <b>RISK-ON</b><em>Confidence 72%</em></div><div className="headerActions"><span className="demo">DEMO DATA</span><button>◌<i>3</i></button><button className="avatar">AK</button></div></header>
<div className="ticker">{[['BTC','$112.5K','+2.84%'],['ETH','$4,286','+4.12%'],['TOTAL','$3.87T','+2.1%'],['BTC.D','57.2%','−0.4%'],['FEAR & GREED','72','GREED']].map((t,i)=><div key={t[0]}><span>{t[0]}</span><b>{t[1]}</b><em className={i===3?'negative':''}>{t[2]}</em></div>)}<p>Updated 4s ago · Mock provider</p></div>
<div className="content"><div className="titleRow"><div><p>MONDAY, AUG 24</p><h1>Market intelligence</h1><span>Unified signals across market, on-chain, social, and derivatives data.</span></div><div className="controls"><button onClick={()=>notify("Latest provider snapshots synchronized")}>↻ Sync data</button><button className="primary" onClick={()=>notify("Alert rule created")}>＋ Create alert</button></div></div>
<section className="stats"><article><label>MARKET BREADTH</label><strong>64.8%</strong><span className="up">▲ 3.2%</span><div className="bar"><i style={{width:'65%'}}/></div><small>64 of top 100 advancing</small></article><article><label>AGGREGATE VOLUME</label><strong>$186.4B</strong><span className="up">▲ 12.6%</span><Sparkline data={[30,36,34,41,39,48,46,57,53,65,61,72]}/></article><article><label>WHALE NET FLOW</label><strong>+$842M</strong><span className="up">ACCUMULATION</span><div className="flow"><i/><i/><i/><i/><i/></div></article><article><label>MARKET RISK</label><strong>36<span>/100</span></strong><span className="low">LOW</span><div className="riskbar"><i/><i/><i/><i/></div></article></section>
<div className="gridMain"><section className="panel opportunities"><div className="panelHead"><div><h2>Top opportunities</h2><p>Ranked by risk-adjusted composite score</p></div><div className="tabs"><button className="chosen">ALL</button><button>LONG</button><button>SHORT</button></div></div><div className="tableTools"><div className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assets"/></div><select value={scan} onChange={e=>setScan(e.target.value)}>{scans.map(s=><option key={s}>{s}</option>)}</select></div><div className="tableWrap"><table><thead><tr><th>#</th><th>ASSET</th><th>PRICE / 24H</th><th>TREND</th><th>SCORE</th><th>DIRECTION</th><th>CONF.</th><th>RISK</th><th></th></tr></thead><tbody>{filtered.map(a=><tr key={a.symbol} className={selected.symbol===a.symbol?'selected':''} onClick={()=>setSelected(a)}><td><b>{a.rank}</b></td><td><div className={`coin c${a.rank}`}>{a.symbol[0]}</div><strong>{a.symbol}<small>{a.name}</small></strong></td><td><b>{a.price}</b><em className={a.change<0?'negative':''}>{a.change>0?'+':''}{a.change}%</em></td><td><Sparkline data={a.spark} down={a.change<0}/></td><td><Ring v={a.score}/></td><td><span className={`signal ${a.direction.toLowerCase()}`}>{a.direction}</span></td><td><b>{a.confidence}%</b></td><td><span className={`risk ${a.risk.toLowerCase()}`}>{a.risk}</span></td><td><button className="why" onClick={e=>{e.stopPropagation();setSelected(a);notify(`${a.symbol} thesis loaded`)}}>WHY? →</button></td></tr>)}</tbody></table></div><button className="viewAll">View top 100 assets →</button></section>
<aside className="panel analyst"><div className="analystTitle"><div className="coin big">{selected.symbol[0]}</div><div><p>AI ANALYST · {selected.symbol}</p><h2>{selected.direction==='SHORT'?'Defensive bias':'Long bias'} <span>{selected.confidence}%</span></h2></div><button>•••</button></div><div className="prob"><label>MODEL OUTPUT <small>Calibrated · v2.4.1</small></label>{[['LONG',selected.direction==='SHORT'?24:selected.confidence,''],['NEUTRAL',selected.direction==='WATCH'?34:15,'neutral'],['SHORT',selected.direction==='SHORT'?66:100-selected.confidence-15,'short']].map(x=><div key={x[0]}><span>{x[0]} <b>{x[1]}%</b></span><i><u className={x[2] as string} style={{width:`${x[1]}%`}}/></i></div>)}</div><div className="thesis"><label>AI INTERPRETATION</label><p>{selected.symbol} shows {selected.whale>75?'strong accumulation with ':''}{selected.tech>75?'constructive momentum':'mixed technical structure'} while derivatives remain {selected.deriv>75?'healthy':'a constraint'}.</p><ul><li><b>Whale accumulation</b><span>+{selected.whale-50} pts</span></li><li><b>Spot demand above VWAP</b><span>+18 pts</span></li><li className="warn"><b>Resistance nearby</b><span>−11 pts</span></li></ul></div><div className="conflict"><span>!</span><div><b>{selected.tech-selected.deriv>12?'SIGNAL CONFLICT':'RISK CHECK'}</b><p>Funding is rising near resistance. Risk engine limits position sizing.</p></div></div><div className="levels"><div><label>INVALIDATION</label><b>{selected.symbol==='BTC'?'$106,800':'−4.8%'}</b></div><div><label>TARGET ZONE</label><b>{selected.symbol==='BTC'?'$118K–$122K':'+8–12%'}</b></div></div><button className="report" onClick={()=>notify(`${selected.symbol} intelligence report prepared`)}>Open full intelligence report →</button></aside></div>
<section className="lower"><article className="panel signals"><div className="panelHead"><div><h2>Live signal stream</h2><p>Cross-provider anomalies and catalysts</p></div><span className="live"><i/> LIVE</span></div>{[['WHALE','BTC exchange outflow','$284M moved to cold storage','2m'],['BREAKOUT','SOL technical breakout','4h resistance cleared on 2.1× volume','8m'],['DERIVATIVES','ETH OI expansion','Price up + OI up; structure confirmed','14m']].map((s,i)=><div className="event" key={s[1]}><span className={`eventIcon e${i}`}>{['◈','↗','≋'][i]}</span><div><label>{s[0]}</label><b>{s[1]}</b><p>{s[2]}</p></div><time>{s[3]}</time></div>)}</article><article className="panel matrix"><div className="panelHead"><div><h2>{selected.symbol} signal matrix</h2><p>Feature attribution and agreement</p></div><span className="score">{selected.score}/100</span></div>{[['Fundamental',selected.fund],['Technical',selected.tech],['Whale',selected.whale],['Derivatives',selected.deriv],['Social',77]].map(([n,v])=><div className="matrixRow" key={n}><span>{n}</span><i><u style={{width:`${v}%`}}/></i><b>{v}</b></div>)}</article><article className="panel portfolio"><div className="panelHead"><div><h2>Paper portfolio</h2><p>Risk-controlled simulation</p></div><span>DEMO</span></div><label>NET LIQUIDATION VALUE</label><strong>$124,862.40</strong><em>+$4,862.40 (+4.05%)</em><div className="portfolioChart"><Sparkline data={[34,37,35,42,46,43,51,56,53,62,67,72]}/></div><div className="portfolioMeta"><span>Exposure <b>42%</b></span><span>Drawdown <b>−1.8%</b></span><span>Sharpe <b>1.64</b></span></div></article></section></div>{notice&&<div className="toast">✓ {notice}</div>}</section></main>}
